fix an error caused by xctestrun v2
Summary:
In the new version of xctestrun, there is a `__xctestrun_metadata__` field to store the format version info. It caused a key error:
```
chengchang-mbp:Shimulator chengchang$ idb xctest install ~/Desktop/simulator/e2e_xctests_sim/UITests/Facebook_iphonesimulator13.2-x86_64.xctestrun
2020-10-26 15:13:20,180 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "idb/cli/main.py", line 273, in gen_main
  File "idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "idb/common/command.py", line 87, in run
    return await self._get_subcommand_for_args(args).run(args)
  File "idb/cli/__init__.py", line 101, in run
    await self._run_impl(args)
  File "idb/cli/__init__.py", line 123, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "idb/cli/commands/xctest.py", line 39, in run_with_client
    async for install_response in client.install_xctest(args.test_bundle_path):
  File "idb/common/logging.py", line 146, in _async_gen_wrapper
    raise ex
  File "idb/common/logging.py", line 121, in _async_gen_wrapper
    async for value in function(*args, **kwargs):
  File "idb/grpc/client.py", line 187, in func_wrapper_gen
    async for item in func(*args, **kwargs):
  File "idb/grpc/client.py", line 559, in install_xctest
    async for response in self._install_to_destination(
  File "idb/grpc/client.py", line 334, in _install_to_destination
    async for message in generator:
  File "idb/grpc/install.py", line 51, in _generate_xctest_chunks
    async for chunk in tar.generate_tar(xctest_paths_to_tar(path)):
  File "idb/grpc/xctest.py", line 74, in xctest_paths_to_tar
    return extract_paths_from_xctestrun(bundle_path)
  File "idb/grpc/xctest.py", line 59, in extract_paths_from_xctestrun
    result.append(test_dict["TestHostPath"].replace("__TESTROOT__", test_root))
KeyError: 'TestHostPath'
```

One example of v2 xctestrun file.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>FacebookUITests</key>
	<dict>
		<key>BlueprintName</key>
		<string>FacebookUITests</string>
		<key>BundleIdentifiersForCrashReportEmphasis</key>
		<array>
			<string>com.facebook.internal.FacebookUITests</string>
		</array>
		<key>CommandLineArguments</key>
		<array/>
		<key>DependentProductPaths</key>
		<array>
			<string>__TESTROOT__/Debug-iphonesimulator/FacebookUITests-Runner.app/PlugIns/FacebookUITests.xctest</string>
		</array>
		<key>EnvironmentVariables</key>
		<dict>
			<key>OS_ACTIVITY_DT_MODE</key>
			<string>YES</string>
			<key>SQLITE_ENABLE_THREAD_ASSERTIONS</key>
			<string>1</string>
		</dict>
		<key>IsUITestBundle</key>
		<true/>
		<key>IsXCTRunnerHostedTestBundle</key>
		<true/>
		<key>TestRegion</key>
		<string></string>
		<key>TestingEnvironmentVariables</key>
		<dict>
			<key>DYLD_FALLBACK_FRAMEWORK_PATH</key>
			<string></string>
			<key>DYLD_FRAMEWORK_PATH</key>
			<string>__TESTROOT__/Debug-iphonesimulator</string>
		</dict>
		<key>ToolchainsSettingValue</key>
		<array/>
		<key>UITargetAppMainThreadCheckerEnabled</key>
		<true/>
		<key>UITargetAppPath</key>
		<string>__TESTROOT__/Debug-iphonesimulator/PerfTestDummyApp.app</string>
		<key>UserAttachmentLifetime</key>
		<string>deleteOnSuccess</string>
	</dict>
	<key>__xctestrun_metadata__</key>
	<dict>
		<key>FormatVersion</key>
		<integer>1</integer>
	</dict>
</dict>
</plist>
```

Reviewed By: c-ryan747

Differential Revision: D24552518

fbshipit-source-id: f09064768735a19abc1ff10cba81e57b9a4778d8