Convert the CircleCI workflow to a GitHub Actions workflow (#861)
Summary:
This pull request converts the CircleCI workflows to GitHub actions workflows. [Github Actions Importer](https://github.com/github/gh-actions-importer) was used to convert the workflows initially, then I edited them manually to correct errors in translation.

**Issues**

1. _facebook/idb/build_and_deploy -> deploy-website_

```
Error: Running "git push" command failed. Does the GitHub user account you are using have push access to the repository?
```

This is due to the fact that `${{ secrets.GITHUB_TOKEN }}` is either undefined or doesn't have the appropriate permissions or scopes enabled to access the repository.

## How did you test this change?

I tested these changes in a [forked repo](https://github.com/robandpdx-org/idb/actions/runs/7717454971).

https://fburl.com/workplace/f6mz6tmw

Pull Request resolved: https://github.com/facebook/idb/pull/861

Reviewed By: Nekitosss

Differential Revision: D56620612

Pulled By: jbardini

fbshipit-source-id: 00b543d0019df4b59324d96582cce321a82c331a