Fix resource leak due to unclosed socket in FBSimulatorXCTestCommands
Summary:
Infer found this, it's legit

```
EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Commands/FBSimulatorXCTestCommands.m:144: error: RESOURCE_LEAK
  resource acquired by call to `socket()` at line 133, column 18 is not released after line 144, column 16.
  142.     if (testManagerSocketString.length == 0) {
  143.       return [[[FBSimulatorError
  144. >       describe:@"Failed to retrieve testmanagerd socket path"]
  145.         logger:logger]
  146.         failInt:error];

EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Commands/FBSimulatorXCTestCommands.m:151: error: RESOURCE_LEAK
  resource acquired by call to `socket()` at line 133, column 18 is not released after line 151, column 22.
  149.     if (![[NSFileManager new] fileExistsAtPath:testManagerSocketString]) {
  150.       return [[[FBSimulatorError
  151. >       describeFormat:@"Simulator indicated unix domain socket for testmanagerd at path %@, but no file was found at that path.", testManagerSocketString]
  152.         logger:logger]
  153.         failInt:error];

EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Commands/FBSimulatorXCTestCommands.m:159: error: RESOURCE_LEAK
  resource acquired by call to `socket()` at line 133, column 18 is not released after line 159, column 22.
  157.     if (strlen(testManagerSocketPath) >= 0x68) {
  158.       return [[[FBSimulatorError
  159. >       describeFormat:@"Unix domain socket path for simulator testmanagerd service '%s' is too big to fit in sockaddr_un.sun_path", testManagerSocketPath]
  160.         logger:logger]
  161.         failInt:error];

EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Commands/FBSimulatorXCTestCommands.m:170: error: RESOURCE_LEAK
  resource acquired by call to `socket()` at line 133, column 18 is not released after line 170, column 16.
  168.     if (connect(socketFD, (struct sockaddr *)&remote, length) == -1) {
  169.       return [[[FBSimulatorError
  170. >       describe:@"Failed to connect to testmangerd socket"]
  171.         logger:logger]
  172.         failInt:error];
```

Reviewed By: zeyadsalloum

Differential Revision: D19410750

fbshipit-source-id: 1b24d83c7f92841ccc5948893c5e655ba5be717e