IDB Logs: Handle Unexpected End of Data
Summary:
When streaming logs in Jest I'm occasionally finding this stack trace in the log output.

```
2026-02-23 05:44:49,347 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "idb/cli/main.py", line 327, in gen_main
    await root_command.run(args)
  File "idb/common/command.py", line 88, in run
    return await self.resolve_command_from_args(args).run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "idb/cli/__init__.py", line 109, in run
    await self._run_impl(args)
  File "idb/cli/__init__.py", line 131, in _run_impl
    await self.run_with_client(args=args, client=client)
  File "idb/cli/commands/log.py", line 52, in run_with_client
    async for chunk in client.tail_logs(
  File "idb/common/logging.py", line 144, in _async_gen_wrapper
    raise ex
  File "idb/common/logging.py", line 119, in _async_gen_wrapper
    async for value in function(*args, **kwargs):
  File "idb/grpc/client.py", line 220, in func_wrapper_gen
    async for item in func(*args, **kwargs):
  File "idb/grpc/client.py", line 1287, in tail_logs
    async for message in self._tail_specific_logs(
  File "idb/grpc/client.py", line 352, in _tail_specific_logs
    yield message.output.decode()
          ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 65535: unexpected end of data
```

That's taken from this run:
`https://www.internalfb.com/intern/testinfra/diagnostics/1125900393905320.281475234576269.1771854297?section=%22logs%22&event=%22xplat%2Fendtoend%2Fjest-e2e%2Fapps%2Fwaios%2F__tests__%2Fbeta%2Fsmoke_tests%2Fcore_user_journey%2FwaiosCreateGroupChatBeta-e2e.js%3A31%22&view_hierarchy=%7B%22tab%22%3A%22Current%22%2C%22selectionPath%22%3Anull%7D&network=%7B%22searchQuery%22%3A%22%22%2C%22showRelevantOnly%22%3Afalse%2C%22filters%22%3A%5B%5D%7D&qpl=%7B%22searchQuery%22%3A%22%22%2C%22filters%22%3A%5B%5D%7D&query=%7B%22version%22%3A1%2C%22filters%22%3A%5B%7B%22key%22%3A%22Search%22%2C%22value%22%3A%22WamEventAppLaunch%22%7D%5D%7D#system_logs_(seconddevice,_last_used))`

The issue appears to be multi-byte UTF-8 characters being split across 64KB gRPC buffer boundaries.

To fix this this replaces naive .decode() with an incremental UTF-8 decoder (codecs.getincrementaldecoder) that buffers incomplete multi-byte sequences across message boundaries and combines them with subsequent chunks.

Reviewed By: xgerrit

Differential Revision: D94083871

fbshipit-source-id: 5632c198e215fff46755a37e015b992f3a4a4474