Fix Infer error due to nullable consumer property
Summary:
This is actually non-nullable, so we just need to adjust the property

```
EndToEndTests/FBSimulatorControl/src/FBControlCore/Utility/FBProcessStream.m:669: error: NULL_DEREFERENCE
  pointer `consumer` last assigned on line 666 could be null and is dereferenced at line 669, column 67.
  667.         id<FBControlCoreLogger> logger = self.logger;
  668.         if (logger) {
  669. >         consumer = [FBCompositeDataConsumer consumerWithConsumers:@[
  670.             consumer,
  671.             [FBLoggingDataConsumer consumerWithLogger:logger],a
```

Reviewed By: zeyadsalloum

Differential Revision: D19411220

fbshipit-source-id: 6e80e5d3793184a572750e239d11a492235a4ca4