Fix uninitialized value for load commands
Summary:
This is actually set in the `fread` command but initializing it appeases infer. No harm in setting it to an empty value

```
EndToEndTests/FBSimulatorControl/src/FBControlCore/Applications/FBBinaryDescriptor.m:168: error: UNINITIALIZED_VALUE
  The value read from command.cmdsize was never initialized.
  166.         return value;
  167.       }
  168. >     offset += command.cmdsize;
  169.     }
  170.     return nil;

EndToEndTests/FBSimulatorControl/src/FBControlCore/Applications/FBBinaryDescriptor.m:187: error: UNINITIALIZED_VALUE
  The value read from command.cmdsize was never initialized.
  185.         return value;
  186.       }
  187. >     offset += command.cmdsize;
  188.     }
  189.     return nil;
```

Reviewed By: zeyadsalloum

Differential Revision: D19411218

fbshipit-source-id: 448db8a7b1b27552f820319e9fc6c5b490285d42