Fix incompatible block types in FBSimulatorBridge.m
Summary:
I'm working on getting RTC's iOS stack to build with Clang 10; I uncovered the
following build errors:

```
fbobjc/EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Management/FBSimulatorBridge.m:211:33: error: incompatible block pointer types sending 'FBFuture * _Nonnull (^)(NSProxy<SimulatorBridge> *__strong)' to parameter of type 'FBFuture * _Nonnull (^ _Nonnull)(id<SimulatorBridge>  _Nonnull __strong)'
    onQueue:self.workQueue fmap:^ FBFuture * _Nonnull (NSProxy<SimulatorBridge> *bridge) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fbobjc/EndToEndTests/FBSimulatorControl/src/FBControlCore/Async/FBFuture.h:212:78: note: passing argument to parameter 'fmap' here
- (FBFuture *)onQueue:(dispatch_queue_t)queue fmap:(FBFuture * (^)(T result))fmap;
                                                                             ^
fbobjc/EndToEndTests/FBSimulatorControl/src/FBSimulatorControl/Management/FBSimulatorBridge.m:232:33: error: incompatible block pointer types sending 'FBFuture * _Nonnull (^)(NSProxy<SimulatorBridge> *__strong)' to parameter of type 'FBFuture * _Nonnull (^ _Nonnull)(id<SimulatorBridge>  _Nonnull __strong)'
    onQueue:self.workQueue fmap:^(NSProxy<SimulatorBridge> *bridge) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fbobjc/EndToEndTests/FBSimulatorControl/src/FBControlCore/Async/FBFuture.h:212:78: note: passing argument to parameter 'fmap' here
- (FBFuture *)onQueue:(dispatch_queue_t)queue fmap:(FBFuture * (^)(T result))fmap;
                                                                             ^
2 errors generated.
```

I fixed the problem by making the `SimulatorBridge` protocol inherit
 the `NSObject` protocol so the problematic blocks can straightforwardly
match the expected types.

Reviewed By: Chocti

Differential Revision: D20132666

fbshipit-source-id: 47ab15fc3352cdd139ab3a346cc24f7733fd8b36