Use asyncio.run() for the CLI entrypoint
Summary:
### Context

This started as a [GitHub PR](https://github.com/facebook/idb/pull/924?fbclid=IwY2xjawSOgEJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZAEwAAEe3Fk94wVh8fJ3IQ51Efiy94dDyW8vINWnimMvESvN4oJsDjqMnH6k3q7KUpE_aem_GJvmB8RRJlZuRJRlcafGww), but the user (`DrunkOnJava`) didn't agree to the Meta CLA, so the PR is not mergable. It fixes a crash in the open source project, so I'm putting it up with some tweaks.

From the original:
```
Python 3.10 deprecated implicit-loop creation in asyncio.get_event_loop();
3.12+ raises RuntimeError("There is no current event loop in thread")
unless an event loop is explicitly set on the current thread. By
Python 3.14 (the default brew formula now) calling 'idb' or 'idb
udid' immediately crashes:
RuntimeError: There is no current event loop in thread 'MainThread'
```

### This diff

Catches the runtime exception from trying to get the event loop and explicitly creates one if necessary. This fixes the crash in newer versions of Python.

Reviewed By: natez0r

Differential Revision: D107536953

fbshipit-source-id: 153e59db5898a7f8ea492679890567e187320145